OBJ_LIST = \
.obj/test.o \


ASM_LIST = \
.obj/test.s \


DEP_LIST = \
.obj/test.dep \


ASM_OBJ_LIST = \


include $(RULES_FILE)


.obj/test.o : ././test.cpp
	$(CC) $(CCOPT) $< -o $@



.obj/test.s : ././test.cpp
	$(CC) -S $(CCOPT) $< -o $@



.obj/test.dep : ././test.cpp
	$(CC) $(CCOPT) -MM -MT .obj/test.o $< -MF $@





ifneq ($(MAKECMDGOALS),clean)

-include $(DEP_FILE)

endif

