"/* Book.ddl */\n"
"//----------------------------------------------------------------------------------------\n"
"//\n"
"//  Project: BookLab 1.00\n"
"//\n"
"//  License: Boost Software License - Version 1.0 - August 17th, 2003\n"
"//\n"
"//            see http://www.boost.org/LICENSE_1_0.txt or the local copy\n"
"//\n"
"//  Copyright (c) 2017 Sergey Strukov. All rights reserved.\n"
"//\n"
"//----------------------------------------------------------------------------------------\n"
"\n"
"int Version = 1 ;\n"
"\n"
"//--- basic types ------------------------------------------------------------------------\n"
"\n"
"type Bool = uint8 ;\n"
"\n"
"Bool True = 1 ;\n"
"\n"
"Bool False = 0 ;\n"
"\n"
"type VColor = uint32 ;\n"
"\n"
"VColor NoColor = 0FFFFFFFFh ;\n"
"\n"
"type Coord = sint32 ;\n"
"\n"
"struct Point\n"
" {\n"
"  Coord x;\n"
"  Coord y;\n"
" };\n"
" \n"
"struct Ratio\n"
" {\n"
"  Coord a;\n"
"  Coord b;\n"
" }; \n"
"\n"
"//--- Text -------------------------------------------------------------------------------\n"
"\n"
"struct Font\n"
" {\n"
"  text face;\n"
"  Coord size;\n"
"  \n"
"  Bool bold = False ;\n"
"  Bool italic = False ;\n"
"  \n"
"  int strength = 0 ;\n"
" };\n"
"\n"
"struct Format\n"
" {\n"
"  Font *font = null ;\n"
"  \n"
"  VColor back = NoColor ;\n"
"  VColor fore = NoColor ;\n"
"  \n"
"  type Effect = uint8 ;\n"
"  \n"
"  const Effect None = 0 ;\n"
"  const Effect Underline = 1 ;\n"
"  const Effect Strikeout = 2 ;\n"
"  \n"
"  Effect effect = None ;\n"
" };\n"
"\n"
"struct OneLine\n"
" {\n"
"  type Align = uint8 ;\n"
"  \n"
"  const Align Left   = 0 ;  \n"
"  const Align Right  = 1 ;  \n"
"  const Align Center = 2 ;\n"
"  \n"
"  Align align = Left ;\n"
" };\n"
" \n"
"struct MultiLine\n"
" {\n"
"  Ratio line_space = {1,1} ;\n"
"  Ratio first_line_space = {2,1} ;\n"
" }; \n"
"\n"
"struct Span\n"
" {\n"
"  text body;\n"
"  \n"
"  Format *fmt = null ;\n"
"  \n"
"  {Link,Page} * ref = null ;\n"
" };\n"
"\n"
"Format DefaultFormat = {} ;\n"
"\n"
"MultiLine DefaultPlacement = {} ;\n"
"\n"
"struct Text\n"
" {\n"
"  Span[] list;\n"
"  \n"
"  Format *fmt = & ?DefaultFormat ;\n"
"  \n"
"  {OneLine,MultiLine} *placement = & ?DefaultPlacement ;\n"
" };\n"
" \n"
"struct FixedSpan\n"
" {\n"
"  text body;\n"
"  \n"
"  Format *fmt = null ;\n"
"  \n"
"  {Link,Page} * ref = null ;\n"
" };\n"
" \n"
"type Line = FixedSpan[] ; \n"
" \n"
"Format DefaultFixedFormat = {} ;\n"
"\n"
"struct FixedText\n"
" {\n"
"  Line[] list;\n"
" \n"
"  Format *fmt = & ?DefaultFixedFormat ;\n"
" }; \n"
"\n"
"//--- Bitmap -----------------------------------------------------------------------------\n"
"\n"
"struct Bitmap\n"
" {\n"
"  text file_name;\n"
" };\n"
"\n"
"//--- TextList ---------------------------------------------------------------------------\n"
"\n"
"struct ListItem\n"
" {\n"
"  text bullet;\n"
"  Frame[] list;\n"
" };\n"
"\n"
"Format DefaultBulletFormat = {} ;\n"
"\n"
"Coord DefaultBulletSpace = 5 ;\n"
"Coord DefaultItemSpace = 0 ;\n"
"\n"
"struct TextList\n"
" {\n"
"  ListItem[] list;\n"
"  \n"
"  Format *bullet_fmt = & ?DefaultBulletFormat ;\n"
"  \n"
"  Coord bullet_space = ?DefaultBulletSpace ;\n"
"  Coord item_space = ?DefaultItemSpace ;\n"
" };\n"
"\n"
"//--- Frame ------------------------------------------------------------------------------\n"
"\n"
"struct SingleLine\n"
" {\n"
"  Ratio width = {1,1} ; \n"
"  VColor line = NoColor ;\n"
" };\n"
" \n"
"struct DoubleLine\n"
" {\n"
"  Ratio width = {1,1} ;\n"
"  VColor gray = NoColor ;\n"
"  VColor snow = NoColor ; \n"
" };\n"
" \n"
"SingleLine DefaultSingleLine = {} ;\n"
"\n"
"DoubleLine DefaultDoubleLine = {} ;  \n"
"\n"
"Point DefaultInner = { 0 , 0 } ;\n"
"\n"
"Point DefaultOuter = { 0 , 0 } ;\n"
"\n"
"struct Frame\n"
" {\n"
"  {Text,FixedText,Bitmap,TextList} *body;\n"
"  \n"
"  {SingleLine,DoubleLine} *line = null ;\n"
"  \n"
"  Point inner = ?DefaultInner ;\n"
"  Point outer = ?DefaultOuter ;\n"
"  \n"
"  VColor col = NoColor ;\n"
" };\n"
" \n"
"//--- Book -------------------------------------------------------------------------------\n"
"\n"
"struct Page\n"
" {\n"
"  text name;\n"
"  \n"
"  Frame[] list;\n"
"  \n"
"  VColor back = NoColor ;\n"
"  VColor fore = NoColor ;\n"
"  \n"
"  Page *up = null ;\n"
"  Page *prev = null ;\n"
"  Page *next = null ;\n"
" };\n"
" \n"
"struct Book\n"
" {\n"
"  text title;\n"
"  \n"
"  Page *start;\n"
"  \n"
"  VColor back = NoColor ;\n"
"  VColor fore = NoColor ;\n"
" }; \n"
"\n"
"struct Link\n"
" {\n"
"  Page *page;\n"
"  ulen frame_index = 0 ;\n"
" };\n"
"\n"
"\n"
" \n"
