/* Book1.Pretext.gen.h */
//----------------------------------------------------------------------------------------
//
//  Project: CCore 3.60
//
//  Tag: Desktop
//
//  License: Boost Software License - Version 1.0 - August 17th, 2003
//
//            see http://www.boost.org/LICENSE_1_0.txt or the local copy
//
//  Copyright (c) 2019 Sergey Strukov. All rights reserved.
//
//----------------------------------------------------------------------------------------

"int Version = 1 ;\n"
"\n"
" \n"
"\n"
"type Bool = uint8 ;\n"
"\n"
"Bool True = 1 ;\n"
"\n"
"Bool False = 0 ;\n"
"\n"
"type VColor = uint32 ;\n"
"\n"
"VColor NoColor = 0FFFFFFFFh ;\n"
"\n"
"type Coord = sint32 ;\n"
"\n"
"struct Point\n"
" {\n"
"  Coord x;\n"
"  Coord y;\n"
" };\n"
" \n"
"struct Ratio\n"
" {\n"
"  Coord a;\n"
"  Coord b;\n"
" }; \n"
"\n"
" \n"
"\n"
"struct Font\n"
" {\n"
"  text face;\n"
"  Coord size;\n"
"  \n"
"  Bool bold = False ;\n"
"  Bool italic = False ;\n"
"  \n"
"  int strength = 0 ;\n"
" };\n"
"\n"
"struct Format\n"
" {\n"
"  Font *font = null ;\n"
"  \n"
"  VColor back = NoColor ;\n"
"  VColor fore = NoColor ;\n"
"  \n"
"  type Effect = uint8 ;\n"
"  \n"
"  const Effect None = 0 ;\n"
"  const Effect Underline = 1 ;\n"
"  const Effect Strikeout = 2 ;\n"
"  \n"
"  Effect effect = None ;\n"
" };\n"
"\n"
"struct Span\n"
" {\n"
"  text body;\n"
"  \n"
"  Format *fmt = null ;\n"
"  \n"
"  {Link,Page} *ref = null ;\n"
" };\n"
"\n"
"struct Link\n"
" {\n"
"  Page *page;\n"
"  ulen[] index_list;\n"
" };\n"
"\n"
" \n"
"\n"
"struct OneLine\n"
" {\n"
"  type Align = uint8 ;\n"
"  \n"
"  const Align Left   = 0 ;  \n"
"  const Align Right  = 1 ;  \n"
"  const Align Center = 2 ;\n"
"  \n"
"  Align align = Left ;\n"
" };\n"
" \n"
"struct MultiLine\n"
" {\n"
"  Ratio line_space = {1,1} ;\n"
"  Ratio first_line_space = {2,1} ;\n"
" }; \n"
"\n"
"Format DefaultFormat = {} ;\n"
"\n"
"MultiLine DefaultPlacement = {} ;\n"
"\n"
"struct Text\n"
" {\n"
"  Span[] list;\n"
"  \n"
"  Format *fmt = & ?DefaultFormat ;\n"
"  \n"
"  {OneLine,MultiLine} *placement = & ?DefaultPlacement ;\n"
" };\n"
" \n"
" \n"
" \n"
"type Line = Span[] ; \n"
" \n"
"Format DefaultFixedFormat = {} ;\n"
"\n"
"struct FixedText\n"
" {\n"
"  Line[] list;\n"
" \n"
"  Format *fmt = & ?DefaultFixedFormat ;\n"
" }; \n"
"\n"
" \n"
"\n"
"struct Bitmap\n"
" {\n"
"  text file_name;\n"
" };\n"
"\n"
" \n"
"\n"
"struct ListItem\n"
" {\n"
"  text bullet;\n"
"  Frame[] list;\n"
" };\n"
"\n"
"Format DefaultBulletFormat = {} ;\n"
"\n"
"Coord DefaultBulletSpace = 5 ;\n"
"Coord DefaultItemSpace = 0 ;\n"
"\n"
"struct TextList\n"
" {\n"
"  ListItem[] list;\n"
"  \n"
"  Format *bullet_fmt = & ?DefaultBulletFormat ;\n"
"  \n"
"  Coord bullet_space = ?DefaultBulletSpace ;\n"
"  Coord item_space = ?DefaultItemSpace ;\n"
" };\n"
"\n"
" \n"
"\n"
"Format DefaultCollapseFormat = {} ;\n"
"\n"
"struct Collapse\n"
" {\n"
"  text title;\n"
"  \n"
"  Frame[] list;\n"
"  \n"
"  Format *collapse_fmt = & ?DefaultCollapseFormat ;\n"
"  \n"
"  Bool open;\n"
"  Bool hide = True ;\n"
" };\n"
" \n"
" \n"
"\n"
"struct Cell\n"
" {\n"
"  Frame[] list;\n"
"  \n"
"  ulen span_x = 1 ;\n"
"  ulen span_y = 1 ;\n"
" };\n"
"\n"
"struct Border\n"
" {\n"
"  Coord space = 0 ; \n"
"  \n"
"  Ratio width = {1,1} ; \n"
"  VColor line = NoColor ;\n"
" };\n"
" \n"
"Border DefaultBorder = {} ; \n"
" \n"
"struct Table\n"
" {\n"
"  Coord[] width;  \n"
" \n"
"  Cell * [][] rows;\n"
"  \n"
"  Border *border = & ?DefaultBorder ;\n"
"  \n"
"  Bool hard = False ;   \n"
" }; \n"
"\n"
" \n"
"\n"
"struct SingleLine\n"
" {\n"
"  Ratio width = {1,1} ; \n"
"  VColor line = NoColor ;\n"
" };\n"
" \n"
"struct DoubleLine\n"
" {\n"
"  Ratio width = {1,1} ;\n"
"  VColor gray = NoColor ;\n"
"  VColor snow = NoColor ; \n"
" };\n"
" \n"
"SingleLine DefaultSingleLine = {} ;\n"
"\n"
"DoubleLine DefaultDoubleLine = {} ;  \n"
"\n"
"Point DefaultInner = { 0 , 0 } ;\n"
"\n"
"Point DefaultOuter = { 0 , 0 } ;\n"
"\n"
"struct Frame\n"
" {\n"
"  {Text,FixedText,Bitmap,TextList,Collapse,Table} *body;\n"
"  \n"
"  {SingleLine,DoubleLine} *line = null ;\n"
"  \n"
"  Point inner = ?DefaultInner ;\n"
"  Point outer = ?DefaultOuter ;\n"
"  \n"
"  VColor col = NoColor ;\n"
" };\n"
" \n"
" \n"
"\n"
"struct Page\n"
" {\n"
"  text name;\n"
"  \n"
"  Frame[] list;\n"
"  \n"
"  VColor back = NoColor ;\n"
"  VColor fore = NoColor ;\n"
"  \n"
"  Page *up   = null ;\n"
"  Page *prev = null ;\n"
"  Page *next = null ;\n"
" };\n"
" \n"
"struct Book\n"
" {\n"
"  text title;\n"
"  \n"
"  Page *start;\n"
"  \n"
"  VColor back = NoColor ;\n"
"  VColor fore = NoColor ;\n"
" };\n"
