# Makefile
#----------------------------------------------------------------------------------------
#
#  Project: CCore 3.01
#
#  License: Boost Software License - Version 1.0 - August 17th, 2003 
#
#            see http://www.boost.org/LICENSE_1_0.txt or the local copy
#
#  Copyright (c) 2017 Sergey Strukov. All rights reserved.
#
#----------------------------------------------------------------------------------------

OPT = -j 8

LIST = Aspect Book BookLab ContourLab DDLDisplay RandomId Sample SubLab TruePrime UserPreference Zipmap WinLab

include ../Target/Makefile.list

